### ISSUE TITLE
How to use sample from wonderful Demo site

### ISSUE THREAD

**Issue by bdrichards** [msalsbery/OpenSeadragonImagingHelper#10]
@msalsbery This is not really an issue, but rather a "request":
In visiting your WONDERFUL live demo site, I want to mimic in my webpage the behavior you demonstrate. Specifically, I would like to have my image "pane" display the navigator as the collapsible (and re-sizable) version you utilize. Is there a way to explain how to easily transfer that behavior to pages that I use for my single "deep zoom" images? I have attempted to dissect the source(s) associated with the demo page, but am failing...... (don't need the VM pane and all that)

**Comment by msalsbery** [comment]
@bdrichards 

So sorry for the extremely long delay.

In case you're wondering at all still...I used Bootstrap (http://getbootstrap.com/) for the UI.

The demo source is in the repository.

I know next to nothing about using Bootstrap beyond what I wanted at the time, so I'm no help there ;)

Best regards!

**Comment by msalsbery** [comment]
@bdrichards  Actually, now that I'm working in it again... it looks like I used jQuery user interface (http://jqueryui.com/) for the collapsible/resizable navigator!

Sorry about that!
