### ISSUE TITLE
Annotation coordinates

### ISSUE THREAD

**Issue by akazer2** [msalsbery/OpenSeadragonImagingHelper#2]
I'm using a custom tool to draw annotation at different zoom levels on images in OpenseaDragon. I'm trying to convert the coordinates to the pixel coordinates at maximum resolution. I can't seem to figure out how to go from the OpenseaDragon.getMousePosition() to coordinates at max resolution. 

Additionally when I convert the mouse position using Physical to DataY the Y coordinate I get is occasionally negative at minimum zoom. Not sure what I'm doing wrong, or if I'm just understanding the library incorrectly. Any help would be appreciated!

**Comment by msalsbery** [comment]
Closing this...

The new home for the OpenSeadragon Imaging plugins is here: https://github.com/openseadragon-imaging
