### ISSUE TITLE
setting initial zoom levels and zoomStep

### ISSUE THREAD

**Issue by sharmaashish** [msalsbery/OpenSeadragonImagingHelper#6]
Does the imaging helper provide methods to set the initial zoom level and the zoom factor? I am trying to setup an environment where the user can move from 1x (initial zoom) to 40x (native resolution) in fixed steps (1x -- 2x -- 4x -- 8x -- 10x -- 20x -- 40x)

**Comment by sharmaashish** [comment]
@msalsbery Welcome back!! Yes, I think if you had a code block or plugin, then it'd be helpful. The project has evolved quite a bit since 2015 - https://sbu-bmi.github.io/quip_distro/

**Comment by msalsbery** [comment]
Closing this...

The new home for the OpenSeadragon Imaging plugins is here: https://github.com/openseadragon-imaging
