### ISSUE TITLE
Trouble with physicalToLogical Y-coord

### ISSUE THREAD

**Issue by MaxDotSouth** [msalsbery/OpenSeadragonImagingHelper#7]
Hi,
my aim is to draw a circle at the very position I do a mouseclick.

Using the code below I get the circle at the correct Xposition but theYposition is only correct when clicking at the top of the image (Y=0). Clicking lower than the top, the circle is above - clicking above the image top, the circle is below the click position.

<pre>
            var logPoint = imagingHelper.physicalToLogicalPoint(event.position);
            var d3Circle = d3.select(overlay.node())
                .append("circle")
                .attr("id", 'circle' + counter++)
                .attr("cx", logPoint.x)
                .attr("cy", logPoint.y)
                .attr("r", 0.04);
</pre>

What did I miss?
Kind Regards, Max

**Comment by msalsbery** [comment]
Hello,

Perhaps you want to use physical coordinates for your circle, so physicalToLogicalPoint isn't needed here?

**Comment by MaxDotSouth** [comment]
I use the osd-svg-overlay plugin to bind the circle to the OSD viewer having it synced with the viewer. That plugin uses logical coordinates, here the plugin's relevant demo code:

<pre>
...
var d3Rect = d3.select(overlay.node()).append("rect")
                        .style('fill', '#f00')
                        .attr("x", 0.5)
                        .attr("width", 0.25)
                        .attr("y", 0.5)
                        .attr("height", 0.25);
...
</pre>

What I did not mention previously, is that I want to store the circle's positions and reconstruct the osd viewer with the circles at a later time.

**Comment by Jondeen** [comment]
Could this be related to  https://github.com/openseadragon/svg-overlay/issues/1 ? I Fixed this only by manually normalizing the Y-values by multiplying by viewer.viewport.contentAspectY. I still can't figure out why this is, but it rectifies my problems.

**Comment by MaxDotSouth** [comment]
Thanks Jondeen - that solved the problem. I did exactly as you wrote:
<pre>
logX = logPoint.x;
logY = logPoint.y * viewer.viewport.contentAspectY;
</pre>

And many many thanks to Mark, Ian & all the others working on OSD!
Kind Regards, Max

**Comment by msalsbery** [comment]
Yes, in this plugin I remove the aspect ratio component from the Y coords - it's more natural to me.
