### ISSUE TITLE
Update for multi-image in OSD 2.0.0

### ISSUE THREAD

**Issue by iangilman** [msalsbery/OpenSeadragonImagingHelper#8]
See https://github.com/openseadragon/openseadragon/issues/748

**Comment by iangilman** [comment]
Thank you for looking into fixing this, @mdcorriveau!

**Comment by mdcorriveau** [comment]
I want your opinion on this, currently the imagingviewer only consider the width to calculate the zoomlevel. Why not use the ratios instead ?

**Comment by iangilman** [comment]
@mdcorriveau Do you mean the OpenSeadragon viewer or this library?

**Comment by mdcorriveau** [comment]
In the library, in this function 

_trackZoomPan: function () {
                var boundsRect = this._viewer.viewport.getBounds(true);
                this._viewportOrigin.x = boundsRect.x;
                this._viewportOrigin.y = boundsRect.y * this.imgAspectRatio;
                this._viewportWidth = boundsRect.width;
                this._viewportHeight = boundsRect.height * this.imgAspectRatio;
                this._viewportCenter.x = this._viewportOrigin.x + (this._viewportWidth / 2.0);
                this._viewportCenter.y = this._viewportOrigin.y + (this._viewportHeight / 2.0);
                this._zoomFactor = this.getViewerContainerSize().x / (this._viewportWidth * this.imgWidth);

                this._raiseImageViewChanged();
            },

**Comment by msalsbery** [comment]
@mdcorriveau  That's a legacy thing...came from Silverlight which was my starting point with Seadragon code. Applies to OSD 1.x as well. Everything there used width and aspect ratio. Since I was doing medical imaging, I preferred working with width/height which is the reason this library exists.

This library definitely needs an OSD 2.0 upgrade. I'll get to it soon hopefully unless someone else does :)

**Comment by mdcorriveau** [comment]
Alright, I'll try do look into, i'm a bit overloaded me too :P

**Comment by iangilman** [comment]
Some progress has been made in https://github.com/msalsbery/OpenSeadragonImagingHelper/pull/14.

What more multi-image support do we want? Would we want to be able to change the world index after it's been initially set? Would we want to be able to have multiple helpers running on the same viewer, one for each image? What else?

**Comment by msalsbery** [comment]
Hi everyone! Sorry for the extreme delay. Will be bringing this into the wonderful world of OpenSeadragon 2.0.0+ very soon.

Thank you for all the contributions in my absence, always very much appreciated!

**Comment by iangilman** [comment]
Awesome :)

**Comment by msalsbery** [comment]
Closing this...

The new home for the OpenSeadragon Imaging plugins is here: https://github.com/openseadragon-imaging

[Here's the new issue...](https://github.com/openseadragon-imaging/openseadragon-imaginghelper/issues/2)
